# Generated by Django 2.2.1 on 2020-01-18 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_out_time', models.DateTimeField(verbose_name='出块时间')),
                ('content_task_num', models.IntegerField(verbose_name='处理内容')),
                ('hash', models.CharField(max_length=256, verbose_name='hash')),
                ('f_hash', models.CharField(max_length=256, verbose_name='父hash')),
                ('miner', models.CharField(max_length=256, verbose_name='矿工')),
                ('size', models.CharField(max_length=125, verbose_name='大小')),
                ('op_num', models.CharField(max_length=125, verbose_name='操作数')),
                ('reward', models.CharField(max_length=125, verbose_name='区块奖励')),
                ('additional_data', models.CharField(max_length=125, verbose_name='附加数据')),
                ('block_depth', models.IntegerField(verbose_name='区块高度')),
            ],
        ),
        migrations.CreateModel(
            name='BlockAcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acount_hash', models.CharField(max_length=256, verbose_name='账户hash')),
                ('balence', models.CharField(max_length=125, verbose_name='余额')),
            ],
        ),
        migrations.CreateModel(
            name='BlockMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=64, verbose_name='NTA节点')),
                ('node_type', models.CharField(max_length=64, verbose_name='节点类型')),
                ('price', models.CharField(max_length=64, verbose_name='节点单价')),
                ('calculation', models.CharField(max_length=64, verbose_name='算力')),
                ('power', models.CharField(max_length=64, verbose_name='功率')),
                ('persent', models.CharField(max_length=64, verbose_name='能效比')),
                ('day_out', models.CharField(max_length=64, verbose_name='日产出')),
                ('day_ele', models.CharField(max_length=64, verbose_name='日电费')),
                ('e_per', models.CharField(max_length=64, verbose_name='电费占比')),
                ('obtain', models.CharField(max_length=64, verbose_name='日净收益')),
            ],
        ),
        migrations.CreateModel(
            name='BlockTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.CharField(max_length=256, verbose_name='标识')),
                ('status', models.IntegerField(choices=[(0, '成功'), (1, '失败'), (2, '进行中')], verbose_name='状态')),
                ('block_belong', models.IntegerField(verbose_name='所属区块')),
                ('create_time', models.DateTimeField(verbose_name='时间')),
                ('receiver', models.CharField(max_length=512, verbose_name='接收方')),
                ('poster', models.CharField(max_length=512, verbose_name='发送方')),
                ('transaction1', models.TextField(verbose_name='代币交易')),
                ('task_num', models.CharField(max_length=125, verbose_name='任务量')),
                ('task_price', models.CharField(max_length=125, verbose_name='任务费用')),
                ('op_num', models.CharField(max_length=125, verbose_name='操作数')),
                ('input_data', models.CharField(max_length=512, verbose_name='输入数据')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, verbose_name='提交数据源路由')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('deadline', models.DateTimeField(verbose_name='接单截止时间')),
                ('category', models.CharField(max_length=32, verbose_name='任务类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='任务总价')),
                ('status', models.IntegerField(choices=[(0, '待接单'), (1, '已接单'), (2, '已付款'), (3, '退款中'), (4, '退款成功'), (5, '已完成')], default=0, verbose_name='任务状态')),
                ('received_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_order_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key', models.CharField(max_length=256, verbose_name='搜索历史')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
