# coding:utf-8
# _author_:Junjie
# date:2018/10/19

# 请求头
command_head = {
    'send_search_task': 'Search_task',
    'response_search_task': 'Ack_Search_task',
    'response_command': 'Ack_command_task',
    'send_search_result': 'Search_result',
    'response_search_result': 'Ack_result',
    'send_search_task_request': 'Search_task_request',
    'no_node':'busy',
    'response_no_task': 'No_task',
    'task_finish': 'Task_finished',
    'command_error': 'error',

    'simnode_task_request': 'simComputing_task_request',
    'send_sim_task': 'simComputing_task',
    'response_sim_task': 'Ack_simComputing_task',
    'send_sim_result': 'simComputing_result',
    'response_sim_result': 'Ack_simComputing_result',
    'send_task_to_sendsimnode': 'simComputing_task',
    'response_sendsimnode_task': 'Ack_simComputing_task',
    'response_sendsimnode_result': 'Ack_simComputing_result',
    'take_sim_result':'take_sim_result',
    'final_sim_result':'final_sim_result',

    'textparsenode_task_request':'textparsenode_task_request',
    'send_textparse_task':'textparse_task',
    'response_textparse_task':'Ack_textparse_task',
    'send_textparse_result':'send_textparse_result',
    'response_textparse_result':'Ack_textparse_result',
    'take_search_result':'take_search_result',
    'final_search_result':'final_search_result',
    'take_textparse_result':'take_textparse_result',
    'final_textparse_result':'final_textparse_result',

    'deal_task_request':'dealnode_task_request',# 任务请求标志头，表示一个任务节点对总控汇报自己空闲，任务节点--->总控
    'send_deal_task':'deal_task',# 任务消息标志头，先从本地发至总控，总控再发至任务节点    本地--->总控--->任务节点，表明发过来的是待执行的任务
    'response_deal_task':'Ack_deal_task',# 任务节点回应总控节点，表明自己受到了任务内容    任务节点--->总控
    'send_deal_result':'send_deal_result',#任务节点向总控发送任务执行结果，   任务节点--->总控
    'response_deal_result':'Ack_deal_result',# 总控节点向任务节点发送收到执行结果的确认消息   ，总控--->任务节点
    'take_deal_result':'take_deal_result',# 本地节点向总控请求任务结果，本地---->总控，总控相当于本地节点的代理，总控发出的任务请求，事实上来源于本地
    'final_deal_result':'final_deal_result',# 总控相本地节点返回任务结果  ，总控--->本地节点

    'image_task_request':'imagenode_task_request',
    'send_image_task':'image_task',
    'response_image_task':'Ack_image_task',
    'send_image_result':'send_image_result',
    'response_image_result':'Ack_image_result',
    'take_image_result':'take_image_result',
    'final_image_result':'final_image_result',

    'linkedin_task_request':'linkedin_task_request',
    'send_linkin_task':'send_linkin_task',
    'response_linkin_task':'response_linkin_task',
    'send_linkin_result':'send_linkin_result',
    'response_linkin_result':'response_linkin_result',
    'take_linkin_result':'take_linkin_result',
    'final_linkin_result':'final_linkin_result',

    'whois_task_request':'whois_task_request',
    'send_whois_task':'send_whois_task',
    'response_whois_task':'response_whois_task',
    'send_whois_result':'send_whois_result',
    'response_whois_result':'response_whois_result',
    'take_whois_result':'take_whois_result',
    'final_whois_result':'final_whois_result',

    'checkmate_task_request':'checkmate_task_request',
    'send_checkmate_task':'send_checkmate_task',
    'response_checkmate_task':'response_checkmate_task',
    'send_checkmate_result':'send_checkmate_result',
    'response_checkmate_result':'response_checkmate_result',
    'take_checkmate_result':'take_checkmate_result',
    'final_checkmate_result':'final_checkmate_result',

    'domain_task_request':'domain_task_request',
    'send_domain_task':'send_domain_task',
    'response_domain_task':'response_domain_task',
    'send_domain_result':'send_domain_result',
    'response_domain_result':'response_domain_result',
    'take_domain_result':'take_domain_result',
    'final_domain_result':'final_domain_result',

    'beenverified_task_request':'beenverified_task_request',
    'send_beenverified_task':'send_beenverified_task',
    'response_beenverified_task':'response_beenverified_task',
    'send_beenverified_result':'send_beenverified_result',
    'response_beenverified_result':'response_beenverified_result',
    'take_beenverified_result':'take_beenverified_result',
    'final_beenverified_result':'final_beenverified_result',

    'qqSpider_task_request':'qqSpider_task_request',
    'send_qqSpider_task':'send_qqSpider_task',
    'response_qqSpider_task':'response_qqSpider_task',
    'send_qqSpider_result':'send_qqSpider_result',
    'response_qqSpider_result':'response_qqSpider_result',
    'take_qqSpider_result':'take_qqSpider_result',
    'final_qqSpider_result':'final_qqSpider_result',

    'facebook_task_request': 'facebook_task_request',
    'send_facebook_task': 'send_facebook_task',
    'response_facebook_task': 'response_facebook_task',
    'send_facebook_result': 'send_facebook_result',
    'response_facebook_result': 'response_facebook_result',
    'take_facebook_result': 'take_facebook_result',
    'final_facebook_result': 'final_facebook_result',

    'wechat_task_request': 'wechat_task_request',
    'send_wechat_task': 'send_wechat_task',
    'response_wechat_task': 'response_wechat_task',
    'send_wechat_result': 'send_wechat_result',
    'response_wechat_result': 'response_wechat_result',
    'take_wechat_result': 'take_wechat_result',
    'final_wechat_result': 'final_wechat_result',

    'search2_task_request': 'search2_task_request',
    'send_search2_task': 'send_search2_task',
    'response_search2_task': 'response_search2_task',
    'send_search2_result': 'send_search2_result',
    'response_search2_result': 'response_search2_result',
    'take_search2_result': 'take_search2_result',
    'final_search2_result': 'final_search2_result',

    # 针对事件及实体,实体关系提取的处理节点封装协议,简称 evtrelner evtrelner
    'evtrelner_task_request':'evtrelnernode_task_request',# 任务请求标志头，表示一个任务节点对总控汇报自己空闲，任务节点--->总控
    'send_evtrelner_task':'evtrelner_task',# 任务消息标志头，先从本地发至总控，总控再发至任务节点    本地--->总控--->任务节点，表明发过来的是待执行的任务
    'response_evtrelner_task':'Ack_evtrelner_task',# 任务节点回应总控节点，表明自己受到了任务内容    任务节点--->总控
    'send_evtrelner_result':'send_evtrelner_result',#任务节点向总控发送任务执行结果，   任务节点--->总控
    'response_evtrelner_result':'Ack_evtrelner_result',# 总控节点向任务节点发送收到执行结果的确认消息   ，总控--->任务节点
    'take_evtrelner_result':'take_evtrelner_result',# 本地节点向总控请求任务结果，本地---->总控，总控相当于本地节点的代理，总控发出的任务请求，事实上来源于本地
    'final_evtrelner_result':'final_evtrelner_result',# 总控相本地节点返回任务结果  ，总控--->本地节点

    'send_nlp_task':'nlp_task',
    'response_nlp_task':'Ack_nlp_task',
    'take_nlp_result':'take_nlp_result',
    'final_nlp_result':'final_nlp_result',
    'nlp_task_request':'nlp_task_request',
    'send_nlp_result':'send_nlp_result',
    'response_nlp_result':'response_nlp_result',

    # 今日头条
    'send_jinri_task_1':'jinri_task_1',
    'response_jinri_task_1':'Ack_jinri_task_1',
    'take_jinri_result_1':'take_jinri_result_1',
    'final_jinri_result_1':'final_jinri_result_1',
    'jinri_request_1':'jinri_task_request_1',
    'send_jinri_result_1':'send_jinri_result_1',
    'response_jinri_result_1':'response_jinri_result_1',

    'send_jinri_task_2': 'jinri_task_2',
    'response_jinri_task_2': 'Ack_jinri_task_2',
    'take_jinri_result_2': 'take_jinri_result_2',
    'final_jinri_result_2': 'final_jinri_result_2',
    'jinri_request_2': 'jinri_task_request_2',
    'send_jinri_result_2': 'send_jinri_result_2',
    'response_jinri_result_2': 'response_jinri_result_2',

    'send_jinri_task_3': 'jinri_task_3',
    'response_jinri_task_3': 'Ack_jinri_task_3',
    'take_jinri_result_3': 'take_jinri_result_3',
    'final_jinri_result_3': 'final_jinri_result_3',
    'jinri_request_3': 'jinri_task_request_3',
    'send_jinri_result_3': 'send_jinri_result_3',
    'response_jinri_result_3': 'response_jinri_result_3',

    'send_jinri_task_6': 'jinri_task_6',
    'response_jinri_task_6': 'Ack_jinri_task_6',
    'take_jinri_result_6': 'take_jinri_result_6',
    'final_jinri_result_6': 'final_jinri_result_6',
    'jinri_request_6': 'jinri_task_request_6',
    'send_jinri_result_6': 'send_jinri_result_6',
    'response_jinri_result_6': 'response_jinri_result_6',

    'send_ltp_task': 'ltp_task',
    'response_ltp_task': 'Ack_ltp_task',
    'take_ltp_result': 'take_ltp_result',
    'final_ltp_result': 'final_ltp_result',
    'ltp_request': 'ltp_task_request',
    'send_ltp_result': 'send_ltp_result',
    'response_ltp_result': 'response_ltp_result',

    'send_stan_nlp_task': 'stan_nlp_task',
    'response_stan_nlp_task': 'Ack_stan_nlp_task',
    'take_stan_nlp_result': 'take_stan_nlp_result',
    'final_stan_nlp_result': 'final_stan_nlp_result',
    'stan_nlp_request': 'stan_nlp_task_request',
    'send_stan_nlp_result': 'send_stan_nlp_result',
    'response_stan_nlp_result': 'response_stan_nlp_result',

    'send_ln_anly_node_task': 'ln_anly_node_task',
    'response_ln_anly_node_task': 'Ack_ln_anly_node_task',
    'take_ln_anly_node_result': 'take_ln_anly_node_result',
    'final_ln_anly_node_result': 'final_ln_anly_node_result',
    'ln_anly_node_request': 'ln_anly_node_request',
    'send_ln_anly_node_result': 'send_ln_anly_node_result',
    'response_ln_anly_node_result': 'response_ln_anly_node_result',

    'send_subj3_node_task': 'subj3_node_task',
    'response_subj3_node_task': 'Ack_subj3_node_task',
    'take_subj3_node_result': 'take_subj3_node_result',
    'final_subj3_node_result': 'final_subj3_node_result',
    'subj3_node_request': 'stan_subj3_node_request',
    'send_subj3_node_result': 'send_subj3_node_result',
    'response_subj3_node_result': 'response_subj3_node_result',

    'send_test_stage0_node_task': 'test_stage0_node_task',
    'response_test_stage0_node_task': 'Ack_test_stage0_node_task',
    'take_test_stage0_node_result': 'take_test_stage0_node_result',
    'final_test_stage0_node_result': 'final_test_stage0_node_result',
    'test_stage0_node_request': 'stan_test_stage0_node_request',
    'send_test_stage0_node_result': 'send_test_stage0_node_result',
    'response_test_stage0_node_result': 'response_test_stage0_node_result',

    'send_gen_ds_strcut_4_rel_9_node_task': 'gen_ds_strcut_4_rel_9_node_task',
    'response_gen_ds_strcut_4_rel_9_node_task': 'Ack_gen_ds_strcut_4_rel_9_node_task',
    'take_gen_ds_strcut_4_rel_9_node_result': 'take_gen_ds_strcut_4_rel_9_node_result',
    'final_gen_ds_strcut_4_rel_9_node_result': 'final_gen_ds_strcut_4_rel_9_node_result',
    'gen_ds_strcut_4_rel_9_node_request': 'stan_gen_ds_strcut_4_rel_9_node_request',
    'send_gen_ds_strcut_4_rel_9_node_result': 'send_gen_ds_strcut_4_rel_9_node_result',
    'response_gen_ds_strcut_4_rel_9_node_result': 'response_gen_ds_strcut_4_rel_9_node_result',

    'send_ie_anly_node_task': 'ie_anly_node_task',
    'response_ie_anly_node_task': 'Ack_ie_anly_node_task',
    'take_ie_anly_node_result': 'take_ie_anly_node_result',
    'final_ie_anly_node_result': 'final_ie_anly_node_result',
    'ie_anly_node_request': 'ie_anly_node_request',
    'send_ie_anly_node_result': 'send_ie_anly_node_result',
    'response_ie_anly_node_result': 'response_ie_anly_node_result',

    'send_ie_anly_node2_task': 'ie_anly_node2_task',
    'response_ie_anly_node2_task': 'Ack_ie_anly_node2_task',
    'take_ie_anly_node2_result': 'take_ie_anly_node2_result',
    'final_ie_anly_node2_result': 'final_ie_anly_node2_result',
    'ie_anly_node2_request': 'ie_anly_node2_request',
    'send_ie_anly_node2_result': 'send_ie_anly_node2_result',
    'response_ie_anly_node2_result': 'response_ie_anly_node2_result',

    'send_pl_anly_node_task': 'pl_anly_node_task',
    'response_pl_anly_node_task': 'Ack_pl_anly_node_task',
    'take_pl_anly_node_result': 'take_pl_anly_node_result',
    'final_pl_anly_node_result': 'final_pl_anly_node_result',
    'pl_anly_node_request': 'pl_anly_node_request',
    'send_pl_anly_node_result': 'send_pl_anly_node_result',
    'response_pl_anly_node_result': 'response_pl_anly_node_result',

    'send_rel_extraction_0_13_node_task': 'rel_extraction_0_13_node_task',
    'response_rel_extraction_0_13_node_task': 'Ack_rel_extraction_0_13_node_task',
    'take_rel_extraction_0_13_node_result': 'take_rel_extraction_0_13_node_result',
    'final_rel_extraction_0_13_node_result': 'final_rel_extraction_0_13_node_result',
    'rel_extraction_0_13_node_request': 'rel_extraction_0_13_node_request',
    'send_rel_extraction_0_13_node_result': 'send_rel_extraction_0_13_node_result',
    'response_rel_extraction_0_13_node_result': 'response_rel_extraction_0_13_node_result',

    'send_rel_get_revised_15_node_task': 'rel_get_revised_15_node_task',
    'response_rel_get_revised_15_node_task': 'Ack_rel_get_revised_15_node_task',
    'take_rel_get_revised_15_node_result': 'take_rel_get_revised_15_node_result',
    'final_rel_get_revised_15_node_result': 'final_rel_get_revised_15_node_result',
    'rel_get_revised_15_node_request': 'rel_get_revised_15_node_request',
    'send_rel_get_revised_15_node_result': 'send_rel_get_revised_15_node_result',
    'response_rel_get_revised_15_node_result': 'response_rel_get_revised_15_node_result',

    'send_rel_get_revised_14_node_task': 'rel_get_revised_14_node_task',
    'response_rel_get_revised_14_node_task': 'Ack_rel_get_revised_14_node_task',
    'take_rel_get_revised_14_node_result': 'take_rel_get_revised_14_node_result',
    'final_rel_get_revised_14_node_result': 'final_rel_get_revised_14_node_result',
    'rel_get_revised_14_node_request': 'rel_get_revised_14_node_request',
    'send_rel_get_revised_14_node_result': 'send_rel_get_revised_14_node_result',
    'response_rel_get_revised_14_node_result': 'response_rel_get_revised_14_node_result',

    'send_stage2_node_task': 'stage2_node_task',
    'response_stage2_node_task': 'Ack_stage2_node_task',
    'take_stage2_node_result': 'take_stage2_node_result',
    'final_stage2_node_result': 'final_stage2_node_result',
    'stage2_node_request': 'stage2_node_request',
    'send_stage2_node_result': 'send_stage2_node_result',
    'response_stage2_node_result': 'response_stage2_node_result',

    'send_anly_node_task': 'anly_node_task',
    'response_anly_node_task': 'Ack_anly_node_task',
    'take_anly_node_result': 'take_anly_node_result',
    'final_anly_node_result': 'final_anly_node_result',
    'anly_node_request': 'anly_node_request',
    'send_anly_node_result': 'send_anly_node_result',
    'response_anly_node_result': 'response_anly_node_result',

    'send_baidu_image_node_task': 'baidu_image_node_task',
    'response_baidu_image_node_task': 'Ack_baidu_image_node_task',
    'take_baidu_image_node_result': 'take_baidu_image_node_result',
    'final_baidu_image_node_result': 'final_baidu_image_node_result',
    'baidu_image_node_request': 'baidu_image_node_request',
    'send_baidu_image_node_result': 'send_baidu_image_node_result',
    'response_baidu_image_node_result': 'response_baidu_image_node_result',

    'send_pre_wash_node22_task': 'pre_wash_node22_task',
    'response_pre_wash_node22_task': 'Ack_pre_wash_node22_task',
    'take_pre_wash_node22_result': 'take_pre_wash_node22_result',
    'final_pre_wash_node22_result': 'final_pre_wash_node22_result',
    'pre_wash_node22_request': 'pre_wash_node22_request',
    'send_pre_wash_node22_result': 'send_pre_wash_node22_result',
    'response_pre_wash_node22_result': 'response_pre_wash_node22_result',

    'send_dianping_dish_task': 'dianping_dish_task',
    'response_dianping_dish_task': 'Ack_dianping_dish_task',
    'take_dianping_dish_result': 'take_dianping_dish_result',
    'final_dianping_dish_result': 'final_dianping_dish_result',
    'dianping_dish_request': 'dianping_dish_request',
    'send_dianping_dish_result': 'send_dianping_dish_result',
    'response_dianping_dish_result': 'response_dianping_dish_result',

    'send_google_translate_task': 'google_translate_task',
    'response_google_translate_task': 'Ack_google_translate_task',
    'take_google_translate_result': 'take_google_translate_result',
    'final_google_translate_result': 'final_google_translate_result',
    'google_translate_request': 'google_translate_request',
    'send_google_translate_result': 'send_google_translate_result',
    'response_google_translate_result': 'response_google_translate_result',

    'send_db_task': 'db_task',
    'response_db_task': 'Ack_db_task',
    'take_db_result': 'take_db_result',
    'final_db_result': 'final_db_result',
    'db_request': 'db_request',
    'send_db_result': 'send_db_result',
    'response_db_result': 'response_db_result',
}
node_type = {
    'simComputing_task':'sim',
     'Search_task':'craw',
    'textparse_task':'textparse',
    'deal_task':'deal',
    'image_task':'image',
    'send_search2_task':'baidu_google_search',
    'send_ltp_task': 'ltp',
    'send_stan_nlp_task': 'stan_nlp',
    'send_ln_anly_node_task': 'ln_anly_node',
    'send_pl_anly_node_task': 'pl_anly_node',
    'send_ie_anly_node_task': 'ie_anly_node',
    'send_ie_anly_node2_task': 'ie_anly_node2',
    'send_subj3_node_task': 'subj3_node',
    'send_test_stage0_node_task': 'test_stage0_node',
    'send_gen_ds_strcut_4_rel_9_node_task': 'gen_ds_strcut_4_rel_9_node',
    'send_rel_extraction_0_13_node_task': 'rel_extraction_0_13_node',
    'send_rel_get_revised_15_node_task': 'rel_get_revised_15_node',
    'send_rel_get_revised_14_node_task': 'rel_get_revised_14_node',
    'send_stage2_node_task': 'stage2_node',
    'send_anly_node_task': 'anly_node',
    'send_baidu_image_node_task': 'baidu_image_node',
    'send_pre_wash_node22_task': 'pre_wash_node22',
    'send_dianping_dish_task': 'dianping_dish',
    'send_google_translate_task': 'google_translate',
}

